import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { http } from '@/lib/http'
import { useTenant } from '@/features/tenants/TenantProvider'

type Product={id:number;name:string;sale_price:string|number}
type Page<T>={data:{data:T[]}}
type Item=Product&{quantity:number;price:number;discount:number}

export function SalePage(){
 const {tenant,branch}=useTenant();const cache=useQueryClient();const [items,setItems]=useState<Item[]>([]);const [search,setSearch]=useState('');const [method,setMethod]=useState('cash');const [tendered,setTendered]=useState('')
 const products=useQuery({queryKey:['products',tenant?.id,search],queryFn:async()=> (await http.get<Page<Product>>('/tenants/'+tenant!.id+'/products',{params:{search}})).data.data.data,enabled:Boolean(tenant)})
 const total=useMemo(()=>items.reduce((sum,item)=>sum+item.quantity*item.price-item.discount,0),[items])
 const change=method==='cash'?Math.max(0,Number(tendered||0)-total):0
 const checkout=useMutation({mutationFn:async()=> (await http.post('/tenants/'+tenant!.id+'/sales/checkout',{branch_id:branch!.id,items:items.map(item=>({product_id:item.id,quantity:item.quantity,unit_price:item.price,discount_amount:item.discount})),payment:tendered?{method,tendered_amount:method==='cash'?Number(tendered):undefined,amount:method==='cash'?undefined:Number(tendered),settle_full:true}:undefined})).data.data,onSuccess:()=>{setItems([]);setTendered('');void cache.invalidateQueries({queryKey:['inventory',tenant?.id,branch?.id]});void cache.invalidateQueries({queryKey:['sales',tenant?.id]})}})
 if(!tenant||!branch)return <p>Seleccioná una empresa y sucursal.</p>
 function add(product:Product){setItems(current=>current.some(item=>item.id===product.id)?current.map(item=>item.id===product.id?{...item,quantity:item.quantity+1}:item):[...current,{...product,quantity:1,price:Number(product.sale_price),discount:0}])}
 return <section className="space-y-5"><h1 className="text-2xl font-bold">Nueva venta</h1><div className="grid gap-5 lg:grid-cols-2"><div className="rounded border bg-white p-4"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar producto" className="w-full rounded border p-2"/>{products.data?.map(p=><button key={p.id} onClick={()=>add(p)} className="mt-2 flex w-full justify-between border p-2">{p.name}<b>{Number(p.sale_price).toLocaleString('es-PY')}</b></button>)}</div><div className="rounded border bg-white p-4">{items.map(item=><div key={item.id} className="flex gap-2 border-b py-2"><span className="flex-1">{item.name}</span><input value={item.quantity} onChange={e=>setItems(rows=>rows.map(row=>row.id===item.id?{...row,quantity:Number(e.target.value)}:row))} type="number" min=".001" className="w-16 border"/><input value={item.price} onChange={e=>setItems(rows=>rows.map(row=>row.id===item.id?{...row,price:Number(e.target.value)}:row))} type="number" min="0" className="w-24 border"/><button onClick={()=>setItems(rows=>rows.filter(row=>row.id!==item.id))}>Quitar</button></div>)}<p className="mt-4 text-xl font-bold">Total: Gs. {total.toLocaleString('es-PY')}</p><label className="mt-3 block">Método<select value={method} onChange={e=>setMethod(e.target.value)} className="ml-2 border"><option value="cash">Efectivo</option><option value="card">Tarjeta</option><option value="transfer">Transferencia</option></select></label><label className="mt-2 block">{method==='cash'?'Efectivo recibido':'Importe a cobrar'}<input value={tendered} onChange={e=>setTendered(e.target.value)} type="number" min="0" className="ml-2 border"/></label>{method==='cash'&&<p className="mt-2 text-lg">Vuelto: Gs. {change.toLocaleString('es-PY')}</p>}<button disabled={!items.length||checkout.isPending} onClick={()=>checkout.mutate()} className="mt-4 w-full rounded bg-slate-900 p-3 text-white">{checkout.isPending?'Procesando…':'Confirmar venta'}</button>{checkout.isError&&<p className="mt-2 text-red-700">No se pudo completar la venta. Revisá stock y pago.</p>}{checkout.isSuccess&&<p className="mt-2 text-emerald-700">Venta registrada; el vuelto fue Gs. {change.toLocaleString('es-PY')}.</p>}</div></div></section>
}
