import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { http } from '@/lib/http'
import { useTenant } from '@/features/tenants/TenantProvider'

type Sale = { id:number; sale_number:string; status:string; total:string|number; paid_amount:string|number; created_at:string; customer?:{name:string}|null; branch?:{name:string}|null }
type SaleDetail = Sale & { items:{id:number;quantity:string|number;unit_price:string|number;discount_amount:string|number;line_total:string|number;product?:{name:string}|null}[]; payments:{id:number;method:string;amount:string|number;tendered_amount?:string|number|null;change_amount?:string|number|null}[] }
type Page<T> = { data:{data:T[]} }
const money=(value:string|number|null|undefined)=>`Gs. ${Number(value ?? 0).toLocaleString('es-PY')}`

export function SalesHistoryPage(){
  const {tenant}=useTenant(); const [status,setStatus]=useState(''); const [selectedId,setSelectedId]=useState<number|null>(null)
  const sales=useQuery({queryKey:['sales',tenant?.id,status],enabled:Boolean(tenant),queryFn:async()=> (await http.get<Page<Sale>>(`/tenants/${tenant!.id}/sales`,{params:status?{status}:undefined})).data.data.data})
  const detail=useQuery({queryKey:['sale',tenant?.id,selectedId],enabled:Boolean(tenant&&selectedId),queryFn:async()=> (await http.get<{data:SaleDetail}>(`/tenants/${tenant!.id}/sales/${selectedId}`)).data.data})
  if(!tenant)return <p>Seleccioná una empresa para consultar sus ventas.</p>
  return <section className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm text-slate-500">{tenant.name}</p><h1 className="text-2xl font-bold">Historial de ventas</h1></div><label className="text-sm">Estado<select value={status} onChange={e=>setStatus(e.target.value)} className="ml-2 rounded border p-2"><option value="">Todos</option><option value="completed">Completadas</option><option value="draft">Borradores</option><option value="cancelled">Canceladas</option></select></label></div>
    <div className="grid gap-5 xl:grid-cols-[1.35fr_.9fr]"><div className="overflow-hidden rounded-lg border bg-white"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-slate-600"><tr><th className="p-3">Venta</th><th className="p-3">Cliente</th><th className="p-3">Estado</th><th className="p-3 text-right">Total</th></tr></thead><tbody>{sales.isLoading&&<tr><td colSpan={4} className="p-5">Cargando…</td></tr>}{sales.data?.map(sale=><tr key={sale.id} onClick={()=>setSelectedId(sale.id)} className={`cursor-pointer border-t hover:bg-slate-50 ${selectedId===sale.id?'bg-slate-100':''}`}><td className="p-3"><b>{sale.sale_number}</b><br/><span className="text-xs text-slate-500">{new Date(sale.created_at).toLocaleString('es-PY')}</span></td><td className="p-3">{sale.customer?.name ?? 'Consumidor final'}</td><td className="p-3"><span className="rounded bg-slate-100 px-2 py-1 text-xs">{sale.status}</span></td><td className="p-3 text-right font-medium">{money(sale.total)}</td></tr>)}{!sales.isLoading&&!sales.data?.length&&<tr><td colSpan={4} className="p-5 text-slate-500">No hay ventas para este filtro.</td></tr>}</tbody></table></div>
      <aside className="rounded-lg border bg-white p-4">{!selectedId&&<p className="text-sm text-slate-500">Elegí una venta para ver su detalle.</p>}{detail.isLoading&&<p>Cargando detalle…</p>}{detail.data&&<div className="space-y-4"><div><h2 className="font-bold">{detail.data.sale_number}</h2><p className="text-sm text-slate-500">{detail.data.branch?.name} · {detail.data.customer?.name ?? 'Consumidor final'}</p></div><div className="space-y-2">{detail.data.items.map(item=><div key={item.id} className="border-b pb-2 text-sm"><div className="flex justify-between"><span>{item.product?.name ?? 'Producto eliminado'}</span><b>{money(item.line_total)}</b></div><span className="text-slate-500">{item.quantity} × {money(item.unit_price)}{Number(item.discount_amount)>0?` · Desc. ${money(item.discount_amount)}`:''}</span></div>)}</div><div className="border-t pt-3"><p className="flex justify-between font-bold"><span>Total</span><span>{money(detail.data.total)}</span></p>{detail.data.payments.map(payment=><div key={payment.id} className="mt-2 text-sm"><p className="flex justify-between"><span>{payment.method}</span><span>{money(payment.amount)}</span></p>{payment.tendered_amount&&<p className="text-slate-500">Recibido: {money(payment.tendered_amount)} · Vuelto: {money(payment.change_amount)}</p>}</div>)}</div></div>}</aside></div>
  </section>
}
