import { type FormEvent, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { createProduct, listProducts, updateProduct, type Product, type ProductPayload } from './api'
import { listCatalog, type CatalogItem } from '@/features/catalogs/api'
import { useTenant } from '@/features/tenants/TenantProvider'
import { isAxiosError } from 'axios'
const empty:ProductPayload={name:'',sku:'',barcode:'',description:'',unit:'unit',cost_price:0,sale_price:0,reorder_point:0,category_id:null,brand_id:null,is_active:true}

export function ProductsPage(){
 const {tenant}=useTenant();const [search,setSearch]=useState('');const [form,setForm]=useState<ProductPayload>(empty);const [editing,setEditing]=useState<number|null>(null);const [error,setError]=useState('');const client=useQueryClient()
 const products=useQuery({queryKey:['products',tenant?.id,search],queryFn:()=>listProducts(tenant!.id,search),enabled:Boolean(tenant)})
 const categories=useQuery({queryKey:['categories',tenant?.id],queryFn:()=>listCatalog('categories',tenant!.id),enabled:Boolean(tenant)})
 const brands=useQuery({queryKey:['brands',tenant?.id],queryFn:()=>listCatalog('brands',tenant!.id),enabled:Boolean(tenant)})
 const save=useMutation({mutationFn:()=>editing?updateProduct(tenant!.id,editing,form):createProduct(tenant!.id,form),onSuccess:()=>{setForm(empty);setEditing(null);setError('');void client.invalidateQueries({queryKey:['products',tenant?.id]})},onError:(e)=>setError(message(e))})
 if(!tenant)return <p>Seleccioná una empresa.</p>
 function submit(e:FormEvent){e.preventDefault();save.mutate()}
 function edit(product:Product){setEditing(product.id);setForm({name:product.name,sku:product.sku,barcode:product.barcode,description:product.description,unit:product.unit,cost_price:Number(product.cost_price),sale_price:Number(product.sale_price),reorder_point:Number(product.reorder_point),category_id:product.category?.id??null,brand_id:product.brand?.id??null,is_active:product.is_active})}
 function field(key:keyof ProductPayload,value:string|number|boolean|null){setForm(current=>({...current,[key]:value}))}
 return <section className="space-y-5"><div><p className="text-sm text-slate-500">Catálogo</p><h1 className="text-2xl font-bold">Productos</h1></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por nombre, SKU o código" className="w-full rounded border p-2"/><div className="grid gap-5 lg:grid-cols-[1fr_360px]"><div className="overflow-hidden rounded border bg-white"><table className="w-full text-sm"><thead><tr><th className="p-3 text-left">Producto</th><th>Categoría</th><th>Marca</th><th>Precio</th><th></th></tr></thead><tbody>{products.data?.map(product=><tr key={product.id} className="border-t"><td className="p-3"><b>{product.name}</b><p className="text-slate-500">{product.sku??'Sin SKU'}</p></td><td>{product.category?.name??'Sin categoría'}</td><td>{product.brand?.name??'Sin marca'}</td><td>{Number(product.sale_price).toLocaleString('es-PY')}</td><td><button onClick={()=>edit(product)}>Editar</button></td></tr>)}</tbody></table></div><form onSubmit={submit} className="space-y-3 rounded border bg-white p-4"><h2 className="font-semibold">{editing?'Editar producto':'Nuevo producto'}</h2><Input value={form.name} onChange={v=>field('name',v)} label="Nombre" required/><Input value={form.sku??''} onChange={v=>field('sku',v||null)} label="SKU"/><Input value={form.barcode??''} onChange={v=>field('barcode',v||null)} label="Código de barras"/><Select label="Categoría" value={form.category_id??''} onChange={v=>field('category_id',v?Number(v):null)} options={categories.data??[]}/><Select label="Marca" value={form.brand_id??''} onChange={v=>field('brand_id',v?Number(v):null)} options={brands.data??[]}/><Input value={form.description??''} onChange={v=>field('description',v||null)} label="Descripción"/><Input value={form.unit??''} onChange={v=>field('unit',v)} label="Unidad"/><Input value={String(form.cost_price??0)} onChange={v=>field('cost_price',Number(v))} label="Costo" type="number"/><Input value={String(form.sale_price??0)} onChange={v=>field('sale_price',Number(v))} label="Precio de venta" type="number"/><Input value={String(form.reorder_point??0)} onChange={v=>field('reorder_point',Number(v))} label="Punto de reposición" type="number"/><label className="flex gap-2 text-sm"><input checked={Boolean(form.is_active)} onChange={e=>field('is_active',e.target.checked)} type="checkbox"/>Activo</label>{error&&<p className="text-sm text-red-600">{error}</p>}<button disabled={save.isPending} className="w-full rounded bg-slate-900 p-2 text-white">{save.isPending?'Guardando…':'Guardar'}</button></form></div></section>
}
function Input({label,value,onChange,type='text',required=false}:{label:string;value:string;onChange:(v:string)=>void;type?:string;required?:boolean}){return <label className="block text-sm">{label}<input required={required} type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded border p-2"/></label>}
function Select({label,value,onChange,options}:{label:string;value:number|string;onChange:(v:string)=>void;options:CatalogItem[]}){return <label className="block text-sm">{label}<select value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded border p-2"><option value="">Sin {label.toLowerCase()}</option>{options.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>}
function message(error:unknown){if(isAxiosError(error)){const data=error.response?.data as {message?:string;errors?:Record<string,string[]>};return Object.values(data?.errors??{})[0]?.[0]??data?.message??'No se pudo guardar el producto.'}return 'No se pudo guardar el producto.'}
