import { useEffect } from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { z } from 'zod'
import { Pencil, Plus } from 'lucide-react'
import { createCatalog, listCatalog, updateCatalog, type CatalogItem } from './api'
import { useTenant } from '@/features/tenants/TenantProvider'
const schema=z.object({name:z.string().min(1,'El nombre es obligatorio'),description:z.string().optional(),is_active:z.boolean()});type FormValues=z.infer<typeof schema>
export function CatalogPage({resource,title}:{resource:'categories'|'brands';title:string}){const {tenant}=useTenant();const qc=useQueryClient();const form=useForm<FormValues>({resolver:zodResolver(schema),defaultValues:{name:'',description:'',is_active:true}});const id=form.watch('_id' as never) as number|undefined;const query=useQuery({queryKey:[resource,tenant?.id],queryFn:()=>listCatalog(resource,tenant!.id),enabled:Boolean(tenant)});const mutation=useMutation({mutationFn:(values:FormValues)=>id?updateCatalog(resource,tenant!.id,id,values):createCatalog(resource,tenant!.id,values),onSuccess:()=>{void qc.invalidateQueries({queryKey:[resource,tenant?.id]});form.reset({name:'',description:'',is_active:true})}});useEffect(()=>{if(!tenant)form.reset()},[tenant,form]);if(!tenant)return <p>Seleccioná una empresa.</p>;return <section className="space-y-6"><div><p className="text-sm text-slate-500">Catálogos</p><h1 className="text-2xl font-bold">{title}</h1></div><div className="grid gap-6 lg:grid-cols-[1fr_340px]"><div className="overflow-hidden rounded-lg border bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="p-3">Nombre</th><th className="p-3">Estado</th><th className="p-3"></th></tr></thead><tbody>{query.isLoading?<tr><td className="p-3" colSpan={3}>Cargando…</td></tr>:query.data?.map(item=><tr key={item.id} className="border-t"><td className="p-3"><strong>{item.name}</strong><p className="text-slate-500">{item.description}</p></td><td className="p-3">{item.is_active?'Activo':'Inactivo'}</td><td className="p-3"><button onClick={()=>form.reset({...item,description:item.description??'',_id:item.id} as FormValues)} aria-label={`Editar ${item.name}`}><Pencil size={16}/></button></td></tr>)}</tbody></table></div><form onSubmit={form.handleSubmit(v=>mutation.mutate(v))} className="space-y-4 rounded-lg border bg-white p-4"><h2 className="font-semibold">{id?'Editar':'Nueva'} {title.slice(0,-1)}</h2><label className="block text-sm">Nombre<input {...form.register('name')} className="mt-1 w-full rounded border p-2"/>{form.formState.errors.name&&<span className="text-red-600">{form.formState.errors.name.message}</span>}</label><label className="block text-sm">Descripción<textarea {...form.register('description')} className="mt-1 w-full rounded border p-2"/></label><label className="flex gap-2 text-sm"><input type="checkbox" {...form.register('is_active')}/> Activo</label><button disabled={mutation.isPending} className="flex items-center gap-2 rounded bg-slate-900 px-3 py-2 text-white"><Plus size={16}/>{mutation.isPending?'Guardando…':'Guardar'}</button></form></div></section>}
